name: braintexts
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pandas=0.24.2
  - pytorch=1.1.0
  - torchvision=0.3.0
  - pydicom>=1.2.2
  - pip=19.1.1
  - pip:
    - pytorch_pretrained_bert
