name: brain-texts
channels:
  - defaults
  - pytorch
  - conda-forge
  - albumentations
dependencies:
  - python=3.7
  - pandas=0.24.2
  - pytorch=1.5.0
  - torchvision=0.6.0
  - cudatoolkit=10.2
  - pydicom=1.2.2
  - pillow=6.0.0
  - opencv=3.4.2
  - keras-gpu=2.2.4
  - albumentations=0.2.2
  - pip=19.1.1
  - pip:
    - pytorch-pretrained-bert
    - nibabel==2.4.1
    - SimpleITK==1.2.0
    - imgaug>=0.2.5,<0.2.7
    - opencv-python-headless
